// Code generated by tygo. DO NOT EDIT.

//////////
// source: model.go

export interface Agent {
  id: string;
  name: string;
  last_seen: string;
  online: boolean;
  latest_snapshot: SnapshotEntry;
}
export interface SnapshotEntry {
  timestamp: number /* int64 */;
  data: SystemInfo;
}
export interface SnapshotEvent {
  agent_id: string;
  snapshot: SnapshotEntry;
}
export interface SnapshotEntryRaw {
  timestamp: number /* int64 */;
  data: any /* json.RawMessage */;
}
export interface GetSnapshotsResponse {
  snapshots: SnapshotEntryRaw[];
}

//////////
// source: system_info.go
/*
Package shared
*/

export interface SystemInfo {
  cpu: CPU[];
  memory: Memory;
  disk: Disk;
  network: Network[];
  temperature: Temperature[];
}
export interface CPU {
  name: string;
  usage_percent: number /* float64 */;
}
export interface Memory {
  total: number /* uint64 */;
  available: number /* uint64 */;
  used: number /* uint64 */;
}
export interface Disk {
  disk_space: DiskSpace;
  disk_io_usage: DiskIOUsage[];
}
export interface DiskSpace {
  path: string;
  total: number /* uint64 */;
  available: number /* uint64 */;
  used: number /* uint64 */;
  usage_percent: number /* float64 */;
}
export interface DiskIOUsage {
  name: string;
  read_mbps: number /* float64 */;
  write_mbps: number /* float64 */;
  io_percent: number /* float64 */;
}
export interface Network {
  name: string;
  rx_bps: number /* float64 */;
  tx_bps: number /* float64 */;
}
export interface Temperature {
  zone: string;
  temp_c: number /* float64 */;
}
