// Code generated by tygo. DO NOT EDIT.

//////////
// source: model.go

export interface Agent {
  guid: string;
  name: string;
  last_seen: string;
  online: boolean;
  latest_snapshot: SnapshotEntry;
}
export interface SnapshotEntry {
  timestamp: number /* int64 */;
  data: SystemInfo;
}
export interface SnapshotEvent {
  agent_guid: string;
  agent_name: string;
  snapshot: SnapshotEntry;
}
export interface SnapshotEntryRaw {
  timestamp: number /* int64 */;
  data: any /* json.RawMessage */;
}
export interface GetSnapshotsResponse {
  snapshots: SnapshotEntryRaw[];
}
export interface UpdateNameRequest {
  name: string;
  guid: string;
}

//////////
// source: system_info.go
/*
Package shared
*/

export interface SystemInfo {
  cpu: CPU[];
  memory: Memory;
  disk: Disk;
  network: Network[];
  temperature?: Temperature[];
  containers?: DockerContainer[];
  agent_ip: string;
  processes: Process[];
}
export interface CPU {
  name: string;
  usage_percent: number /* float64 */;
}
export interface Memory {
  total: number /* uint64 */;
  available: number /* uint64 */;
  used: number /* uint64 */;
}
export interface Disk {
  disk_space: DiskSpace;
  disk_io_usage: DiskIOUsage[];
}
export interface DiskSpace {
  path: string;
  total: number /* uint64 */;
  available: number /* uint64 */;
  used: number /* uint64 */;
  usage_percent: number /* float64 */;
}
export interface DiskIOUsage {
  name: string;
  read_mbps: number /* float64 */;
  write_mbps: number /* float64 */;
  io_percent: number /* float64 */;
}
export interface Network {
  name: string;
  rx_bps: number /* float64 */;
  tx_bps: number /* float64 */;
}
export interface Temperature {
  zone: string;
  temp_c: number /* float64 */;
}
export interface DockerPort {
  private_port: number /* int */;
  public_port: number /* int */;
  type: string;
}
export interface DockerContainer {
  name: string;
  state: string;
  image: string;
  status: string;
  ports: DockerPort[];
}
export interface Process {
  pid: number /* int */;
  user: string;
  cpu: number /* float64 */;
  memory: number /* float64 */;
  rss: number /* uint64 */;
  uptime: number /* int */;
  name: string;
  command: string;
}
