// Code generated by tygo. DO NOT EDIT.
import type { SystemInfo } from './types';
//////////
// source: api.go

export interface API {
}

//////////
// source: model.go

export interface Agent {
  id: string;
  name: string;
  last_seen: string;
  online: boolean;
  latest_snapshot: SnapshotEntry;
}
export interface SnapshotEntry {
  timestamp: string;
  data: SystemInfo;
}
export interface GetSnapshotsResponse {
  snapshots: SnapshotEntry[];
}
