// Code generated by tygo. DO NOT EDIT.

//////////
// source: system_info.go
/*
Package shared
*/

export interface SystemInfo {
  cpu_usage: CPUUsage;
  memory: MemoryUsage;
  disk_space: DiskSpace;
  disk_io_usage: DiskIOUsage[];
  net_usage: NetUsage[];
  temperature: TempInfo[];
}
export interface CPUUsage {
  cpu_info: CPUInfo[];
  cpu_avg: number /* float64 */;
}
export interface CPUInfo {
  name: string;
  usage_percent: number /* float64 */;
}
export interface MemoryUsage {
  total: number /* uint64 */;
  available: number /* uint64 */;
  used: number /* uint64 */;
}
export interface DiskSpace {
  path: string;
  total: number /* uint64 */;
  available: number /* uint64 */;
  used: number /* uint64 */;
  usage_percent: number /* float64 */;
}
export interface DiskIOUsage {
  name: string;
  read_mbps: number /* float64 */;
  write_mbps: number /* float64 */;
  io_percent: number /* float64 */;
}
export interface NetUsage {
  name: string;
  rx_bps: number /* float64 */;
  tx_bps: number /* float64 */;
}
export interface TempInfo {
  zone: string;
  temp_c: number /* float64 */;
}
