// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"
)

type Agent struct {
	ID       string
	Name     string
	LastSeen time.Time
}

type Snapshot struct {
	ID        int64
	AgentID   string
	Timestamp time.Time
	Data      string
}
