// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"time"
)

type Agent struct {
	Guid      string         `json:"guid"`
	Name      sql.NullString `json:"name"`
	MachineID string         `json:"machine_id"`
	LastSeen  time.Time      `json:"last_seen"`
}

type Snapshot struct {
	ID        int64     `json:"id"`
	AgentGuid string    `json:"agent_guid"`
	Timestamp time.Time `json:"timestamp"`
	Data      string    `json:"data"`
}
