// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const deleteSnapshotsOlderThan = `-- name: DeleteSnapshotsOlderThan :exec
DELETE FROM snapshots WHERE timestamp < ?
`

func (q *Queries) DeleteSnapshotsOlderThan(ctx context.Context, timestamp time.Time) error {
	_, err := q.db.ExecContext(ctx, deleteSnapshotsOlderThan, timestamp)
	return err
}

const getAgent = `-- name: GetAgent :one
SELECT guid, name, machine_id, last_seen FROM agents WHERE guid = ? LIMIT 1
`

func (q *Queries) GetAgent(ctx context.Context, guid string) (Agent, error) {
	row := q.db.QueryRowContext(ctx, getAgent, guid)
	var i Agent
	err := row.Scan(
		&i.Guid,
		&i.Name,
		&i.MachineID,
		&i.LastSeen,
	)
	return i, err
}

const getAlertConfig = `-- name: GetAlertConfig :one
SELECT id, cpu_threshold, mem_threshold, disk_threshold, offline_mins, tolerance_mins, webhook_url FROM alert_configs LIMIT 1
`

func (q *Queries) GetAlertConfig(ctx context.Context) (AlertConfig, error) {
	row := q.db.QueryRowContext(ctx, getAlertConfig)
	var i AlertConfig
	err := row.Scan(
		&i.ID,
		&i.CpuThreshold,
		&i.MemThreshold,
		&i.DiskThreshold,
		&i.OfflineMins,
		&i.ToleranceMins,
		&i.WebhookUrl,
	)
	return i, err
}

const getLatestSnapshot = `-- name: GetLatestSnapshot :one
SELECT id, agent_guid, timestamp, data FROM snapshots
WHERE agent_guid = ?
ORDER BY timestamp DESC
LIMIT 1
`

func (q *Queries) GetLatestSnapshot(ctx context.Context, agentGuid string) (Snapshot, error) {
	row := q.db.QueryRowContext(ctx, getLatestSnapshot, agentGuid)
	var i Snapshot
	err := row.Scan(
		&i.ID,
		&i.AgentGuid,
		&i.Timestamp,
		&i.Data,
	)
	return i, err
}

const insertSnapshot = `-- name: InsertSnapshot :exec
INSERT INTO snapshots (agent_guid, timestamp, data)
VALUES (?, ?, ?)
`

type InsertSnapshotParams struct {
	AgentGuid string    `json:"agent_guid"`
	Timestamp time.Time `json:"timestamp"`
	Data      string    `json:"data"`
}

func (q *Queries) InsertSnapshot(ctx context.Context, arg InsertSnapshotParams) error {
	_, err := q.db.ExecContext(ctx, insertSnapshot, arg.AgentGuid, arg.Timestamp, arg.Data)
	return err
}

const listAgents = `-- name: ListAgents :many
SELECT guid, name, machine_id, last_seen FROM agents ORDER BY last_seen DESC
`

func (q *Queries) ListAgents(ctx context.Context) ([]Agent, error) {
	rows, err := q.db.QueryContext(ctx, listAgents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Agent
	for rows.Next() {
		var i Agent
		if err := rows.Scan(
			&i.Guid,
			&i.Name,
			&i.MachineID,
			&i.LastSeen,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSnapshotsByRange = `-- name: ListSnapshotsByRange :many
SELECT id, agent_guid, timestamp, data
FROM snapshots
WHERE agent_guid = ? AND timestamp >= ? AND timestamp <= ?
ORDER BY timestamp ASC
`

type ListSnapshotsByRangeParams struct {
	AgentGuid   string    `json:"agent_guid"`
	Timestamp   time.Time `json:"timestamp"`
	Timestamp_2 time.Time `json:"timestamp_2"`
}

func (q *Queries) ListSnapshotsByRange(ctx context.Context, arg ListSnapshotsByRangeParams) ([]Snapshot, error) {
	rows, err := q.db.QueryContext(ctx, listSnapshotsByRange, arg.AgentGuid, arg.Timestamp, arg.Timestamp_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Snapshot
	for rows.Next() {
		var i Snapshot
		if err := rows.Scan(
			&i.ID,
			&i.AgentGuid,
			&i.Timestamp,
			&i.Data,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAgentName = `-- name: UpdateAgentName :exec
UPDATE agents
SET name = ?
WHERE guid = ?
`

type UpdateAgentNameParams struct {
	Name sql.NullString `json:"name"`
	Guid string         `json:"guid"`
}

func (q *Queries) UpdateAgentName(ctx context.Context, arg UpdateAgentNameParams) error {
	_, err := q.db.ExecContext(ctx, updateAgentName, arg.Name, arg.Guid)
	return err
}

const upsertAgent = `-- name: UpsertAgent :one
INSERT INTO agents (guid, machine_id, last_seen)
VALUES (?, ?, ?)
ON CONFLICT(machine_id) DO UPDATE SET
    last_seen = excluded.last_seen
RETURNING guid, name, machine_id, last_seen
`

type UpsertAgentParams struct {
	Guid      string    `json:"guid"`
	MachineID string    `json:"machine_id"`
	LastSeen  time.Time `json:"last_seen"`
}

func (q *Queries) UpsertAgent(ctx context.Context, arg UpsertAgentParams) (Agent, error) {
	row := q.db.QueryRowContext(ctx, upsertAgent, arg.Guid, arg.MachineID, arg.LastSeen)
	var i Agent
	err := row.Scan(
		&i.Guid,
		&i.Name,
		&i.MachineID,
		&i.LastSeen,
	)
	return i, err
}

const upsertAlertConfig = `-- name: UpsertAlertConfig :one
INSERT INTO alert_configs (id, cpu_threshold, mem_threshold, disk_threshold, offline_mins, tolerance_mins, webhook_url)
VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET
    id = excluded.id
RETURNING id, cpu_threshold, mem_threshold, disk_threshold, offline_mins, tolerance_mins, webhook_url
`

type UpsertAlertConfigParams struct {
	ID            int64          `json:"id"`
	CpuThreshold  sql.NullInt64  `json:"cpu_threshold"`
	MemThreshold  sql.NullInt64  `json:"mem_threshold"`
	DiskThreshold sql.NullInt64  `json:"disk_threshold"`
	OfflineMins   sql.NullInt64  `json:"offline_mins"`
	ToleranceMins sql.NullInt64  `json:"tolerance_mins"`
	WebhookUrl    sql.NullString `json:"webhook_url"`
}

func (q *Queries) UpsertAlertConfig(ctx context.Context, arg UpsertAlertConfigParams) (AlertConfig, error) {
	row := q.db.QueryRowContext(ctx, upsertAlertConfig,
		arg.ID,
		arg.CpuThreshold,
		arg.MemThreshold,
		arg.DiskThreshold,
		arg.OfflineMins,
		arg.ToleranceMins,
		arg.WebhookUrl,
	)
	var i AlertConfig
	err := row.Scan(
		&i.ID,
		&i.CpuThreshold,
		&i.MemThreshold,
		&i.DiskThreshold,
		&i.OfflineMins,
		&i.ToleranceMins,
		&i.WebhookUrl,
	)
	return i, err
}
