// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"
	"time"
)

const deleteSnapshotsOlderThan = `-- name: DeleteSnapshotsOlderThan :exec
DELETE FROM snapshots WHERE timestamp < ?
`

func (q *Queries) DeleteSnapshotsOlderThan(ctx context.Context, timestamp time.Time) error {
	_, err := q.db.ExecContext(ctx, deleteSnapshotsOlderThan, timestamp)
	return err
}

const getAgent = `-- name: GetAgent :one
SELECT id, name, last_seen FROM agents WHERE id = ? LIMIT 1
`

func (q *Queries) GetAgent(ctx context.Context, id string) (Agent, error) {
	row := q.db.QueryRowContext(ctx, getAgent, id)
	var i Agent
	err := row.Scan(&i.ID, &i.Name, &i.LastSeen)
	return i, err
}

const getLatestSnapshot = `-- name: GetLatestSnapshot :one
SELECT id, agent_id, timestamp, data FROM snapshots
WHERE agent_id = ?
ORDER BY timestamp DESC
LIMIT 1
`

func (q *Queries) GetLatestSnapshot(ctx context.Context, agentID string) (Snapshot, error) {
	row := q.db.QueryRowContext(ctx, getLatestSnapshot, agentID)
	var i Snapshot
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.Timestamp,
		&i.Data,
	)
	return i, err
}

const insertSnapshot = `-- name: InsertSnapshot :exec
INSERT INTO snapshots (agent_id, timestamp, data)
VALUES (?, ?, ?)
`

type InsertSnapshotParams struct {
	AgentID   string    `json:"agent_id"`
	Timestamp time.Time `json:"timestamp"`
	Data      string    `json:"data"`
}

func (q *Queries) InsertSnapshot(ctx context.Context, arg InsertSnapshotParams) error {
	_, err := q.db.ExecContext(ctx, insertSnapshot, arg.AgentID, arg.Timestamp, arg.Data)
	return err
}

const listAgents = `-- name: ListAgents :many
SELECT id, name, last_seen FROM agents ORDER BY last_seen DESC
`

func (q *Queries) ListAgents(ctx context.Context) ([]Agent, error) {
	rows, err := q.db.QueryContext(ctx, listAgents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Agent
	for rows.Next() {
		var i Agent
		if err := rows.Scan(&i.ID, &i.Name, &i.LastSeen); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSnapshotsByRange = `-- name: ListSnapshotsByRange :many
SELECT id, agent_id, timestamp, data
FROM snapshots
WHERE agent_id = ? AND timestamp >= ? AND timestamp <= ?
ORDER BY timestamp ASC
`

type ListSnapshotsByRangeParams struct {
	AgentID     string    `json:"agent_id"`
	Timestamp   time.Time `json:"timestamp"`
	Timestamp_2 time.Time `json:"timestamp_2"`
}

func (q *Queries) ListSnapshotsByRange(ctx context.Context, arg ListSnapshotsByRangeParams) ([]Snapshot, error) {
	rows, err := q.db.QueryContext(ctx, listSnapshotsByRange, arg.AgentID, arg.Timestamp, arg.Timestamp_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Snapshot
	for rows.Next() {
		var i Snapshot
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.Timestamp,
			&i.Data,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAgent = `-- name: UpsertAgent :exec
INSERT INTO agents (id, name, last_seen)
VALUES (?, ?, ?)
ON CONFLICT(id) DO UPDATE SET
    name      = excluded.name,
    last_seen = excluded.last_seen
`

type UpsertAgentParams struct {
	ID       string    `json:"id"`
	Name     string    `json:"name"`
	LastSeen time.Time `json:"last_seen"`
}

func (q *Queries) UpsertAgent(ctx context.Context, arg UpsertAgentParams) error {
	_, err := q.db.ExecContext(ctx, upsertAgent, arg.ID, arg.Name, arg.LastSeen)
	return err
}
